name: grid20m-venv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.7.22=hbcca054_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.9=h7f8727e_0
  - pip=23.2.1=pyhd8ed1ab_0
  - python=3.8.17=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.0.0=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py38h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - alabaster==0.7.13
      - asdf==2.15.0
      - asdf-astropy==0.4.0
      - asdf-coordinates-schemas==0.2.0
      - asdf-standard==1.0.3
      - asdf-transform-schemas==0.3.0
      - asdf-unit-schemas==0.1.0
      - asdf-wcs-schemas==0.1.1
      - astropy==5.2.2
      - attrs==23.1.0
      - babel==2.12.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - contourpy==1.1.0
      - cycler==0.11.0
      - cygrid==2.0.3.dev132
      - cython==3.0.0
      - docutils==0.20.1
      - dysh==0.1.0
      - fonttools==4.42.0
      - gbtgridder==2.0.0
      - grid20m==0.0.0
      - gwcs==0.18.3
      - idna==3.4
      - imagesize==1.4.1
      - importlib-metadata==6.8.0
      - importlib-resources==6.0.0
      - jinja2==3.1.2
      - jmespath==1.0.1
      - jsonschema==4.17.3
      - kiwisolver==1.4.4
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.7.2
      - mdit-py-plugins==0.4.0
      - mdurl==0.1.2
      - myst-parser==2.0.0
      - ndcube==2.1.3
      - numpy==1.24.4
      - packaging==23.1
      - pandas==2.0.3
      - pillow==10.0.0
      - pkgutil-resolve-name==1.3.10
      - pyerfa==2.0.0.3
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.12.2
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyyaml==6.0.1
      - requests==2.31.0
      - scipy==1.10.1
      - semantic-version==2.10.0
      - six==1.16.0
      - snowballstemmer==2.2.0
      - specutils==1.11.0
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - tzdata==2023.3
      - urllib3==2.0.4
      - zipp==3.16.2
prefix: /home/scratch/psalas/.conda/grid20m-venv
